- hosts: localhost
  user: ubuntu
  gather_facts: no
  tasks:
    - name: stop processes
      ignore_errors: true
      shell:
        cmd: sudo kill -9 $(sudo lsof -i -P -n | awk '/LISTEN/ && /{{ item }}/' | awk '{print $2}')
      loop:
        - 9000
        - 80
